Repository jonahkimm/MenuMap, pull requests merged in 2023-11, with the labels that each got.

#5 Issue #2. Layout of Restaurant result cards.
  Milestone1AIDisclosure/P1_AI_Declaration_Aryaman_Bahuguna_301563474.pdf
  Milestone1AIDisclosure/ProjectMileston1_AI_Declaration_Aarham_Haider_301462422.pdf
  Milestone1AIDisclosure/ProjectMileston1_AI_Declaration_Jeet_Patel_301573108.pdf
  Milestone1AIDisclosure/ProjectMileston1_AI_Declaration_Jonah_Kim_301395290.pdf
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/mappin.png
  src/assets/testpic.jpg
  src/components/Rescard.jsx
  src/index.js
Labels: enhancement, design

#6 Issue #1: Implemented simple side bar and title
  src/App.js
  src/components/Sidebar.jsx
Labels: enhancement, design

#8 Issue 7: Separated Rescard to be a class component so they will make class obj…
  src/App.js
  src/components/MiddleSearch.jsx
  src/components/Rescard.jsx
Labels: enhancement, design

#11 Implemented header, updated sidebar and middle
  src/App.js
  src/assets/home.png
  src/assets/search.png
  src/components/Header.jsx
  src/components/MiddleSearch.jsx
  src/components/Sidebar.jsx
  src/index.js
Labels: enhancement, design

#12 Issue #9. Separated restaurant cards and on hover indicates the card …
  src/components/Header.jsx
  src/components/MiddleSearch.jsx
  src/components/Rescard.jsx
Labels: enhancement, design

#13 Implemented useFetch hook to handle api calls with axios
  package-lock.json
  package.json
  src/components/Header.jsx
  src/hooks/useFetch.js
Labels: enhancement

#14 Updated Google maps
  src/App.js
  src/components/EmbededMap.jsx
Labels: enhancement

#19 Integrated API with search to dynamically display content and fixed infinite useFetch loop
  src/components/MiddleSearch.jsx
  src/components/MiddleSearch.test.js
  src/hooks/useFetch.js
Labels: enhancement

#24 Added recommendations popup and modified style
  src/components/MiddleSearch.jsx
  src/components/RecommendCard.jsx
  src/components/RecommendPopup.jsx
  src/components/Recommendations.jsx
  src/components/Rescard.jsx
Labels: enhancement

#26 Updated popup window Rescard and added User Location hook
  src/components/MiddleSearch.jsx
  src/components/PopupInfo.jsx
  src/components/Rescard.jsx
  src/hooks/useLocationFetch.js
Labels: enhancement, design

#27 Updated styling for Recommend and Middle Search
  src/components/MiddleSearch.jsx
  src/components/PopupInfo.jsx
  src/components/RecommendCard.jsx
  src/components/RecommendPopup.jsx
Labels: design

#28 Added map component using google maps api
  package-lock.json
  package.json
  src/App.js
  src/components/Map.jsx
Labels: enhancement

#29 Styled google maps. Will now take location data from user and show on…
  package-lock.json
  package.json
  src/components/Map.jsx
  src/components/MiddleSearch.jsx
  src/components/Rescard.jsx
  src/hooks/useLocationFetch.js
Labels: enhancement, design
