Repository jonahkimm/MenuMap, pull requests merged in 2023-12, with the labels that each got.

#33 Integrated grids for dynamic resizing
  src/App.js
  src/components/Container.jsx
  src/components/MiddleSearch.jsx
  src/components/RecommendCard.jsx
  src/components/Recommendations.jsx
  src/components/Rescard.jsx
  src/components/Sidebar.jsx
Labels: design

#32 Google maps API
  public/favicon.ico
  public/logo512.png
  src/assets/mappin.png
  src/components/EmbededMap.jsx
  src/components/Map.jsx
  src/components/Recommendations.jsx
Labels: enhancement

#34 Relocated API calls to container parent component
  src/components/Container.jsx
  src/components/Map.jsx
  src/components/MiddleSearch.jsx
  src/components/MiddleSearch.test.js
  src/components/__snapshots__/MiddleSearch.test.js.snap
Labels: bug

#35 Implemented dynamic markers based on restaurant query
  src/components/Container.jsx
  src/components/Map.jsx
  src/components/Recommendations.jsx
Labels: enhancement

#36 Reco to restaurant search
  src/components/Container.jsx
  src/components/Context.jsx
  src/components/Map.jsx
  src/components/RecommendCard.jsx
  src/components/RecommendPopup.jsx
  src/components/Recommendations.jsx
  src/hooks/useFetch.js
  src/hooks/useSearch.js
  src/index.js
Labels: enhancement

#39 Implemented new search bar feature
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Container.jsx
  src/components/Map.jsx
  src/components/MiddleSearch.jsx
  src/components/RecommendCard.jsx
  src/components/Recommendations.jsx
  src/components/Rescard.jsx
  src/components/Welcome.jsx
  src/hooks/useFetch.js
  src/hooks/useSearch.js
Labels: enhancement, design

#40 Integration tests
  package-lock.json
  package.json
  src/components/EmbededMap.jsx
  src/components/Map.jsx
  src/components/Map.test.js
  src/components/Welcome.jsx
  src/components/Welcome.test.js
Labels: test

#43 Cleaned up the app with styling and consistency, and fixed pin bug
  src/components/Container.jsx
  src/components/ContainerSearch-to-Map.test.js
  src/components/Map.jsx
  src/components/MiddleSearch.jsx
  src/components/PopupInfo.jsx
  src/components/RecommendCard.jsx
  src/components/RecommendPopup.jsx
  src/components/Recommendations.jsx
  src/components/Rescard.jsx
  src/components/Welcome-to-Map.test.js
  src/components/Welcome.jsx
  src/hooks/useSearch.js
  src/math.js
  src/math.test.js
Labels: bug, design
